all: bin\
	bin/limit \
	bin/1d_rand \
	bin/index_order \
	bin/contiguous3d \
	bin/temperature \
	bin/ff2grey

bin/limit: limit.c
	$(COMPILE)

bin/1d_rand: 1d_rand.c
	$(COMPILE)

bin/index_order: index_order.c
	$(COMPILE)

bin/contiguous3d: contiguous3d.c
	$(COMPILE)

bin/temperature: temperature.c
	$(COMPILE)

bin/ff2grey: ff2grey.c
	$(COMPILE)

include ../progs.mk
