all: bin bin/limit bin/1d_rand bin/index_order bin/contiguous3d

bin/limit: limit.c
	$(COMPILE)

bin/1d_rand: 1d_rand.c
	$(COMPILE)

bin/index_order: index_order.c
	$(COMPILE)

bin/contiguous3d: contiguous3d.c
	$(COMPILE)

include ../progs.mk
